-- ================== IF Engine 메타 테이블 (MS SQL Server) ==================
-- 더존 I/F 서버가 MSSQL인 경우 엔진 DB도 MSSQL로 맞추면 운영이 단순해진다.
CREATE TABLE IF_MASTER (
    IF_ID         NVARCHAR(30)   PRIMARY KEY,
    IF_NAME       NVARCHAR(100),
    SRC_SYSTEM    NVARCHAR(30),
    TGT_SYSTEM    NVARCHAR(30),
    SRC_TYPE      NVARCHAR(10),
    TGT_TYPE      NVARCHAR(10),
    SRC_CONFIG    NVARCHAR(MAX),
    TGT_CONFIG    NVARCHAR(MAX),
    CRON_EXPR     NVARCHAR(30),
    DUP_KEY_COLS  NVARCHAR(200),
    USE_YN        NCHAR(1) DEFAULT 'Y',
    DESCRIPTION   NVARCHAR(500)
);

CREATE TABLE IF_MAPPING (
    MAPPING_ID     BIGINT IDENTITY(1,1) PRIMARY KEY,
    IF_ID          NVARCHAR(30) NOT NULL,
    SRC_FIELD      NVARCHAR(100),
    TGT_FIELD      NVARCHAR(100),
    TRANSFORM_RULE NVARCHAR(200),
    SORT_ORDER     INT DEFAULT 0
);

CREATE TABLE IF_LOG (
    LOG_ID        BIGINT IDENTITY(1,1) PRIMARY KEY,
    IF_ID         NVARCHAR(30),
    EXEC_ID       NVARCHAR(36),
    REC_KEY       NVARCHAR(200),
    STATUS        NVARCHAR(10),
    PAYLOAD_SRC   NVARCHAR(MAX),
    PAYLOAD_TGT   NVARCHAR(MAX),
    ERROR_MSG     NVARCHAR(2000),
    RETRY_OF      BIGINT,
    TRIGGERED_BY  NVARCHAR(20),
    CREATED_AT    DATETIME2
);

CREATE INDEX IX_IF_LOG_KEY ON IF_LOG (IF_ID, REC_KEY, STATUS);
CREATE INDEX IX_IF_LOG_DT  ON IF_LOG (CREATED_AT);

CREATE TABLE CODE_MAP (
    CODE_MAP_ID   BIGINT IDENTITY(1,1) PRIMARY KEY,
    GROUP_ID      NVARCHAR(30)  NOT NULL,
    SRC_CODE      NVARCHAR(50)  NOT NULL,
    TGT_CODE      NVARCHAR(50)  NOT NULL,
    DESCRIPTION   NVARCHAR(200),
    SORT_ORDER    INT DEFAULT 0,
    CONSTRAINT UX_CODE_MAP UNIQUE (GROUP_ID, SRC_CODE)
);
